// Select the HTML button, input, and div element with their appropriate ID and store it in a constant variable
const generateBtn = document.querySelector('#generate');
const promptInput = document.querySelector('#prompt');
const outlineDiv = document.querySelector('#outline');

// Add an event listener to the 'generate' button that listens for a 'click' event and runs an async function
generateBtn.addEventListener('click', async () => {
  
  // Store the value of the 'prompt' input field in a constant variable
  const prompt = promptInput.value;
  if (!prompt) return;
  
  // Send a POST request to the OpenAI API endpoint using the 'fetch' function
  const response = await fetch('https://api.openai.com/v1/engines/davinci/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer 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'
    },
    // send the request body as a JSON string that includes the 'prompt' and several other API parameters, which controls how the response will generate
    body: JSON.stringify({
      prompt,
      temperature: 0.7,
      max_tokens: 700,
      top_p: 0.9,
      frequency_penalty: 0,
      presence_penalty: 0
    })
  });
  
  // Parse the API response as a JSON object and store it in a constant variable
  const data = await response.json();

  console.log(data);

  // Set the text content of the 'outline' div to be the completed text generated by the API
  outlineDiv.textContent = data.choices[0].text;
});
